import 'achievement_models.dart';

abstract final class AchievementCatalog {
  static const originalCatalogItemIds = <String>{
    'ITEM-A-01',
    'ITEM-A-02',
    'ITEM-A-03',
    'ITEM-A-04',
    'ITEM-A-05',
    'ITEM-B-01',
    'ITEM-B-02',
    'ITEM-B-03',
    'ITEM-B-04',
    'ITEM-B-05',
    'ITEM-C-01',
    'ITEM-C-02',
    'ITEM-C-03',
    'ITEM-C-04',
    'ITEM-C-05',
    'ITEM-CONV-01',
    'ITEM-CONV-02',
    'ITEM-CONV-03',
  };

  /// The current game has Aura transformations rather than separate playable
  /// characters. Version 1 freezes those five domain IDs as the original roster.
  static const originalCharacterRosterIds = <String>{
    'FORM-01',
    'FORM-02',
    'FORM-03',
    'FORM-04',
    'FORM-05',
  };

  static const maximumAuraStateId = 'FORM-05';
  static const fortyTwoTechniqueId = 'TECH-06';

  static final definitions = List<AchievementDefinition>.unmodifiable([
    _standard(
      AuraAchievement.firstMovement,
      AchievementMetric.auraProducingMovements,
      1,
      5,
      'Primeiro Movimento',
      'Produza aura com seu primeiro movimento.',
      'First Movement',
      'Produce aura with your first movement.',
    ),
    _standard(
      AuraAchievement.firstSix,
      AchievementMetric.sixMovements,
      1,
      5,
      'Six',
      'Faça seu primeiro Six.',
      'Six',
      'Perform your first Six.',
    ),
    _standard(
      AuraAchievement.firstSeven,
      AchievementMetric.sevenMovements,
      1,
      5,
      'Seven',
      'Faça seu primeiro Seven.',
      'Seven',
      'Perform your first Seven.',
    ),
    _bigStandard(
      AuraAchievement.sixSeven,
      AchievementMetric.totalAura,
      '67',
      10,
      'SixSeven!',
      'Farme um total de 67 de aura.',
      'SixSeven!',
      'Farm a total of 67 aura.',
    ),
    _standard(
      AuraAchievement.firstPurchase,
      AchievementMetric.purchases,
      1,
      10,
      'Primeira Aquisição',
      'Compre sua primeira melhoria.',
      'First Purchase',
      'Buy your first upgrade.',
    ),
    _standard(
      AuraAchievement.firstAutomaticProduction,
      AchievementMetric.automaticProductionSources,
      1,
      10,
      'Agora Vai Sozinho',
      'Comece a produzir aura automaticamente.',
      'Now It Runs Itself',
      'Start producing aura automatically.',
    ),
    _standard(
      AuraAchievement.firstOfflineReward,
      AchievementMetric.offlineRewardsCollected,
      1,
      15,
      'A Aura Não Dorme',
      'Colete aura produzida enquanto você estava fora.',
      'Aura Never Sleeps',
      'Collect aura produced while you were away.',
    ),
    _incremental(
      AuraAchievement.manualMovements100,
      AchievementMetric.manualMovements,
      100,
      10,
      'Cento e Poucos',
      'Realize 100 movimentos manuais.',
      'A Hundred or So',
      'Perform 100 manual movements.',
    ),
    _incremental(
      AuraAchievement.manualMovements1000,
      AchievementMetric.manualMovements,
      1000,
      25,
      'Mãos à Obra',
      'Realize 1.000 movimentos manuais.',
      'Hands at Work',
      'Perform 1,000 manual movements.',
    ),
    _incremental(
      AuraAchievement.manualMovements10000,
      AchievementMetric.manualMovements,
      10000,
      50,
      'Tendinite Espiritual',
      'Realize 10.000 movimentos manuais.',
      'Spiritual Tendinitis',
      'Perform 10,000 manual movements.',
    ),
    _bigStandard(
      AuraAchievement.totalAura1000,
      AchievementMetric.totalAura,
      '1000',
      15,
      'Aura de Cria',
      'Farme um total de mil de aura.',
      'Rookie Aura',
      'Farm a total of one thousand aura.',
    ),
    _bigStandard(
      AuraAchievement.totalAura1Million,
      AchievementMetric.totalAura,
      '1000000',
      30,
      'Aura Industrial',
      'Farme um total de um milhão de aura.',
      'Industrial Aura',
      'Farm a total of one million aura.',
    ),
    _bigStandard(
      AuraAchievement.totalAura1Billion,
      AchievementMetric.totalAura,
      '1000000000',
      50,
      'Aura Lendária',
      'Farme um total de um bilhão de aura.',
      'Legendary Aura',
      'Farm a total of one billion aura.',
    ),
    _bigStandard(
      AuraAchievement.totalAura1Trillion,
      AchievementMetric.totalAura,
      '1000000000000',
      75,
      'Aura Cósmica',
      'Farme um total de um trilhão de aura.',
      'Cosmic Aura',
      'Farm a total of one trillion aura.',
    ),
    _bigStandard(
      AuraAchievement.totalAura1Quintillion,
      AchievementMetric.totalAura,
      '1000000000000000000',
      100,
      'Isso Está Escalando',
      'Farme um total de um quintilhão de aura.',
      'This Is Escalating',
      'Farm a total of one quintillion aura.',
    ),
    _standard(
      AuraAchievement.tenItems,
      AchievementMetric.unlockedItems,
      10,
      30,
      'Colecionador',
      'Desbloqueie dez itens diferentes.',
      'Collector',
      'Unlock ten different items.',
    ),
    _setStandard(
      AuraAchievement.originalItemCatalog,
      AchievementMetric.originalItemCatalog,
      75,
      'Catálogo Completo',
      'Desbloqueie todos os itens do catálogo original.',
      'Complete Catalog',
      'Unlock every item in the original catalog.',
    ),
    _standard(
      AuraAchievement.fiveCharacters,
      AchievementMetric.unlockedCharacters,
      3,
      30,
      'Elenco de Respeito',
      'Desbloqueie três Transformações de Aura.',
      'A Solid Cast',
      'Unlock three Aura Transformations.',
    ),
    _setStandard(
      AuraAchievement.originalCharacterRoster,
      AchievementMetric.originalCharacterRoster,
      75,
      'Todo Mundo Tem Aura',
      'Desbloqueie todas as Transformações de Aura originais.',
      'Everyone Has Aura',
      'Unlock every original Aura Transformation.',
    ),
    _setStandard(
      AuraAchievement.maximumAuraState,
      AchievementMetric.maximumAuraState,
      50,
      'Aura Máxima',
      'Alcance o estado visual máximo de aura.',
      'Maximum Aura',
      'Reach the maximum visual aura state.',
    ),
    const AchievementDefinition(
      key: AuraAchievement.fortyTwo,
      type: AchievementType.standard,
      visibility: AchievementVisibility.hidden,
      points: 40,
      metric: AchievementMetric.fortyTwo,
      listOrder: 21,
      namePtBr: 'Forty Two',
      descriptionPtBr:
          'Desbloqueie a resposta para a vida o universo e tudo mais.',
      nameEnUs: 'Forty Two',
      descriptionEnUs: 'Unlock the answer to life the universe and everything.',
    ),
    _incremental(
      AuraAchievement.sevenDistinctDays,
      AchievementMetric.distinctPlayDays,
      7,
      30,
      'Sete Dias de Aura',
      'Jogue Aura Shift em sete dias diferentes.',
      'Seven Days of Aura',
      'Play Aura Shift on seven different days.',
    ),
    _incremental(
      AuraAchievement.thirtyDistinctDays,
      AchievementMetric.distinctPlayDays,
      30,
      75,
      'Fiel ao Farm',
      'Jogue Aura Shift em trinta dias diferentes.',
      'Faithful to the Farm',
      'Play Aura Shift on thirty different days.',
    ),
    _bigStandard(
      AuraAchievement.auraPerSecond67,
      AchievementMetric.auraPerSecond,
      '67',
      15,
      'Sessenta e Sete por Segundo',
      'Produza pelo menos 67 de aura por segundo.',
      'Sixty-Seven per Second',
      'Produce at least 67 aura per second.',
    ),
    _bigStandard(
      AuraAchievement.auraPerSecond1Million,
      AchievementMetric.auraPerSecond,
      '1000000',
      50,
      'Produção de Respeito',
      'Produza pelo menos um milhão de aura por segundo.',
      'Serious Production',
      'Produce at least one million aura per second.',
    ),
    _bigStandard(
      AuraAchievement.singleMovement1Million,
      AchievementMetric.maximumAuraPerMovement,
      '1000000',
      50,
      'Um Movimento Absurdo',
      'Produza um milhão de aura em um único movimento.',
      'One Absurd Movement',
      'Produce one million aura in a single movement.',
    ),
  ]);

  static AchievementDefinition definitionFor(AuraAchievement key) =>
      definitions.firstWhere((definition) => definition.key == key);

  static AchievementDefinition _standard(
    AuraAchievement key,
    AchievementMetric metric,
    int threshold,
    int points,
    String ptName,
    String ptDescription,
    String enName,
    String enDescription,
  ) =>
      AchievementDefinition(
        key: key,
        type: AchievementType.standard,
        visibility: AchievementVisibility.revealed,
        points: points,
        metric: metric,
        intThreshold: threshold,
        listOrder: key.index + 1,
        namePtBr: ptName,
        descriptionPtBr: ptDescription,
        nameEnUs: enName,
        descriptionEnUs: enDescription,
      );

  static AchievementDefinition _bigStandard(
    AuraAchievement key,
    AchievementMetric metric,
    String threshold,
    int points,
    String ptName,
    String ptDescription,
    String enName,
    String enDescription,
  ) =>
      AchievementDefinition(
        key: key,
        type: AchievementType.standard,
        visibility: AchievementVisibility.revealed,
        points: points,
        metric: metric,
        bigIntThreshold: BigInt.parse(threshold),
        listOrder: key.index + 1,
        namePtBr: ptName,
        descriptionPtBr: ptDescription,
        nameEnUs: enName,
        descriptionEnUs: enDescription,
      );

  static AchievementDefinition _setStandard(
    AuraAchievement key,
    AchievementMetric metric,
    int points,
    String ptName,
    String ptDescription,
    String enName,
    String enDescription,
  ) =>
      AchievementDefinition(
        key: key,
        type: AchievementType.standard,
        visibility: AchievementVisibility.revealed,
        points: points,
        metric: metric,
        listOrder: key.index + 1,
        namePtBr: ptName,
        descriptionPtBr: ptDescription,
        nameEnUs: enName,
        descriptionEnUs: enDescription,
      );

  static AchievementDefinition _incremental(
    AuraAchievement key,
    AchievementMetric metric,
    int steps,
    int points,
    String ptName,
    String ptDescription,
    String enName,
    String enDescription,
  ) =>
      AchievementDefinition(
        key: key,
        type: AchievementType.incremental,
        visibility: AchievementVisibility.revealed,
        points: points,
        metric: metric,
        requiredSteps: steps,
        listOrder: key.index + 1,
        namePtBr: ptName,
        descriptionPtBr: ptDescription,
        nameEnUs: enName,
        descriptionEnUs: enDescription,
      );
}
